// flow-typed signature: 408cb6894bef528990cb5d072d6c3c91
// flow-typed version: <<STUB>>/crypto_v6.11.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto' {
  declare module.exports: any;
}
