// flow-typed signature: 43874951c16c5597b495954b0bba3fa0
// flow-typed version: <<STUB>>/http_v^3.10.10/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
